### ISSUE TITLE
IndexOutOfRangeException after a while of playing

### ISSUE THREAD

**Issue by EikeB89** [janholo/ProgrammingChallenge1#1]
IndexOutOfRangeException in Methode SetBall nach einer Weile. Der Ball wurde vom NaiveController von Rechts nach Links gespielt. 

**StackTrace:**
   at ConsolePong.View.ConsoleView.SetBall(Ball ball) in C:\_Git\AIT\Challenge1\View\ConsoleView.cs:line 137
   at ConsolePong.View.ConsoleView.Show(GameState gameState, String leftControllerName, String rightControllerName) in C:\_Git\AIT\Challenge1\View\ConsoleView.cs:line 75
   at ConsolePong.GameLogic.GameRunner.Run(GameSettings gameSettings, IView view, IController leftController, IController rightController) in C:\_Git\AIT\Challenge1\GameLogic\GameRunner.cs:line 17
   at ConsolePong.Program.Run() in C:\_Git\AIT\Challenge1\Program.cs:line 46
   at ConsolePong.Program.Main() in C:\_Git\AIT\Challenge1\Program.cs:line 17

**Verfügbare Daten:**
![image](https://user-images.githubusercontent.com/53081495/61535944-bf3cd600-aa33-11e9-80e5-ed397485c00d.png)

**Spielfeld:**
![image](https://user-images.githubusercontent.com/53081495/61535800-6ff6a580-aa33-11e9-8c39-138b8af9bd43.png)

**Comment by janholo** [comment]
Vielen Dank, ich schaue es mir an.

**Comment by janholo** [comment]
Sollte repariert sein
